name: expense_claims_app
description: Mobile application for the MPower team to claim their expenses

version: 1.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.12.9+5
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  flutter_svg: 0.14.1
  rxdart: 0.22.2
  material_design_icons_flutter: 3.2.4595
  firebase_core: ^0.4.0+9
  firebase_crashlytics: ^0.1.0+3
  font_awesome_flutter: ^8.5.0
  datetime_picker_formfield: 0.4.3
  image_picker: ^0.6.1+11
  permission_handler: 3.3.0
  flutter_masked_text: 0.8.0
  firebase_storage: 3.0.6
  scrollable_bottom_sheet: ^0.2.1
  auto_size_text: ^2.1.0
  timeago: ^2.0.21
  cached_network_image: ^1.1.2+1
  carousel_slider: ^1.3.0
  photo_view: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.svg
